rule smoketest:
    input:
        metrics="build/smoketest/metrics.parquet",
        demo="build/smoketest/demo.parquet",
    script:
        "scripts/smoketest_summary.py"


include: "rules/download.smk"
include: "rules/smoketest.smk"
