[project]
name = "mediparse"
version = "0.1.0"
description = "Repozitar k bakalarske praci zamerene na NLP v lekarskych zpravach. Obsahuje experimenty s klasifikaci nalezu, NER a porovnani klasickych ML metod a transformatorovych modelu na datove sade MIMIC-IV."
readme = "README.md"
authors = [
    { name = "Martin Žoha", email = "193829878+Zohino@users.noreply.github.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = []

[project.urls]
Repository = "https://github.com/Zohino/mediparse"

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.18.0",
    "import-linter[ui]>=2.15",
    "ruff>=0.16.6",
    "ty>=0.0.78",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true

[tool.importlinter]
root_packages = ["mediparse", "tests", "workflow"]
include_external_packages = true
exclude_type_checking_imports = true

# Architektura:
# application a infrastructure:
# - mohou záviset na domain
# - nesmí záviset jedna na druhé
#
# domain:
# - nesmí záviset na application
# - nesmí záviset na infrastructure
[[tool.importlinter.contracts]]
name = "Vrstvená architektura mediparse"
type = "layers"
layers = [
    "mediparse.application | mediparse.infrastructure",
    "mediparse.domain",
]

# Zabraňuje cyklickým závislostem mezi siblings
# uvnitř mediparse (včetně vnořených modulů).
[[tool.importlinter.contracts]]
name = "Mediparse je acyklické"
type = "acyclic_siblings"
ancestors = [
    "mediparse",
]

# workflow je orchestrace mimo samotný package.
# Mediparse může být použit workflow,
# ale nikdy nesmí záviset na workflow.
[[tool.importlinter.contracts]]
name = "Mediparse nesmí záviset na workflow"
type = "forbidden"
source_modules = [
    "mediparse",
]
forbidden_modules = [
    "workflow",
]

[[tool.importlinter.contracts]]
name = "Workflow importuje přímo pouze mediparse.application"
type = "forbidden"
allow_indirect_imports = true
source_modules = [
    "workflow",
]
forbidden_modules = [
    "mediparse.domain",
    "mediparse.infrastructure",
]

[[tool.importlinter.contracts]]
name = "Testy nejsou součástí mediparse"
type = "forbidden"
source_modules = [
    "mediparse",
]
forbidden_modules = [
    "tests",
]

[tool.ruff]
extend-exclude = ["workflow"]   # Snakemake používá vlastní importy a fmt
fix = true
preview = true
show-fixes = true

[tool.ruff.lint]
future-annotations = true
select = ["ALL"]
# recommended ignore list https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
    "tab-indentation",
    "indentation-with-invalid-multiple",
    "indentation-with-invalid-multiple-comment",
    "over-indented",
    "incorrect-blank-line-before-class",
    "docstring-tab-indentation",
    "triple-single-quotes",
    "bad-quotes-inline-string",
    "bad-quotes-multiline-string",
    "bad-quotes-docstring",
    "avoidable-escaped-quote",
    "unnecessary-escaped-quote",
    "missing-trailing-comma",
    "prohibited-trailing-comma",
    "line-too-long",

    # Vyjmutá pravidla pro nadbytečnost nebo striktnost, která není v projektu vyžadována
    "missing-copyright-notice", # Copyright je uveden v LICENSE souboru a odkazován v pyproject.toml
]

[tool.ruff.lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"

[tool.ruff.lint.pylint]
max-nested-blocks = 3

[tool.ruff.format]
docstring-code-format = true
