project:
  type: default
  output-dir: ../results/eda

engine: knitr
lang: cs
author: Martin Žoha
bibliography: references.bib
toc: true
toc-title: Obsah
number-sections: true

crossref:
  sec-prefix: ""

format:
  typst:
    papersize: a4
    citeproc: true

execute:
  freeze: auto
  echo: false
  message: false
  warning: false
