{
  "hash": "bc67e28379a2c35a7d2601b4f59c84e1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Explorační analýza datové sady: přehled korpusu MIMIC-IV\"\nabstract: |\n  Dokument zahajuje explorační analýzu datové sady, na které práce staví. Popisuje zdroje dat (MIMIC-IV a MIMIC-IV-Note), cestu dat od stažení po dotazování a ochranu dat podle licence. Přehled korpusu uvádí pro každou tabulku počet záznamů, počet sloupců a velikost souboru a porovnává počty záznamů v databázi s manifestem validace. Dokument tak vymezuje východiska, na kterých staví další části analýzy.\n---\n\n\n\n# Úvod\n\nTento sešit je prvním z řady sešitů explorační analýzy. Jeho úlohou je charakterizovat datovou sadu, na které stojí celá práce, a zdokumentovat, odkud data pocházejí a jak se k nim dokument dostává. Sešit si klade tři cíle:\n\n- popsat zdroje dat a jejich licenční omezení,\n- popsat cestu dat od stažení po dotazování a způsob, jakým dokument chrání data pacientů,\n- uvést přehled korpusu: tabulky, jejich obsah, počty záznamů a velikost.\n\nPráce vychází z návrhu, podle kterého jsou primárním korpusem propouštěcí zprávy (tabulka `discharge`), radiologické zprávy jsou doplňkové a štítky klasifikace se odvozují z diagnóz ICD (tabulka `diagnoses_icd`). Dokument tato východiska nepotvrzuje ani nevyvrací; ověřuje jen, že potřebné tabulky existují a zda jsou úplné.\n\nData pocházejí ze dvou projektů PhysioNetu [@goldberger2000]. Strukturovaná data hospitalizací poskytuje MIMIC-IV [@mimiciv; @johnson2023], volné texty zpráv MIMIC-IV-Note [@mimicivnote]. Oba projekty podléhají smlouvě o užívání dat (DUA). Dokument proto zveřejňuje jen agregované výsledky, v nichž jsou kategorie s méně než deseti záznamy potlačeny.\n\nDokument je členěn takto. Kapitola @sec-data popisuje zdroje dat a metody. Kapitola @sec-prehled uvádí přehled korpusu. Kapitola @sec-shrnuti shrnuje výsledky a kapitola @sec-omezeni jmenuje omezení. Příloha A dokumentuje provenance renderu.\n\n# Data a metody {#sec-data}\n\nPráce používá dva projekty PhysioNetu. MIMIC-IV, verze 3.1 [@mimiciv], obsahuje strukturovaná data hospitalizací; dokument z něj čte moduly `hosp` (pacienti, přijetí, diagnózy, výkony, léky). MIMIC-IV-Note, verze 2.2 [@mimicivnote], obsahuje deidentifikované volné texty a dokument z něj čte propouštěcí a radiologické zprávy. Popis MIMIC-IV a jeho vzniku uvádí @johnson2023.\n\nData podléhají DUA. Z toho plyne několik pravidel, která dokument dodržuje:\n\n- řádková data a texty zpráv se nevypisují,\n- výsledky jsou agregáty a kategorie s méně než deseti záznamy se sloučí do řádku „ostatní (n < 10)“ a jejich popisky se nezobrazí; číslo pod prahem se zobrazí jako „< 10“,\n- skutečná data zpracovává jen autor mimo automatizované nástroje; automatizovaná kontrola běží nad syntetickými tabulkami stejného tvaru a ověřuje, že jejich obsah neunikl do výstupu.\n\nData procházejí těmito kroky: stažení souborů `csv.gz` z PhysioNetu, ověření jejich otisků SHA-256 proti oficiálním hodnotám, validace (počet záznamů a sloupců), převod na parquet a dotazování přes DuckDB. Převod do parquetu zachovává všechny sloupce jako text a počet záznamů ověřuje proti validaci. Dotazy nad parquetem provádí DuckDB s omezenou pamětí a s dočasnými soubory mimo verzovaný obsah repozitáře.\n\nReprodukovatelnost zajišťují dva mechanismy. Výsledky výpočtů se ukládají do zmražené podoby (`freeze`), takže dokument lze znovu vyrenderovat bez přístupu k datům. Příloha A uvádí provenance renderu: revizi kódu, otisk zámku prostředí, zdroj dat a verze použitých nástrojů.\n\n# Přehled korpusu {#sec-prehled}\n\nDatabáze obsahuje 12 tabulek. @tbl-korpus uvádí pro každou z nich projekt a modul, popis obsahu a plánované využití v práci, počet záznamů v databázi, počet sloupců a velikost komprimovaného souboru podle manifestu validace. Využití tabulek v práci vychází z návrhu práce.\n\n\n::: {#tbl-korpus .cell tbl-cap='Tabulky korpusu: zdroj, obsah a využití, počet záznamů, počet sloupců a velikost souboru (MB).' tbl-colwidths='[22,16,30,10,12,10]'}\n::: {.cell-output-display}\n\n\n|Tabulka            |Zdroj                |Obsah a využití                                                                |    Záznamů| Sloupců|    MB|\n|:------------------|:--------------------|:------------------------------------------------------------------------------|----------:|-------:|-----:|\n|`admissions`       |MIMIC-IV (hosp)      |Hospitalizace: čas přijetí a propuštění, typ přijetí; vazba zpráv na pacienty. |    546 028|      16|    20|\n|`d_icd_diagnoses`  |MIMIC-IV (hosp)      |Číselník diagnóz ICD; názvy ke kódům.                                          |    112 107|       3|     1|\n|`d_icd_procedures` |MIMIC-IV (hosp)      |Číselník výkonů ICD; názvy ke kódům.                                           |     86 423|       3|     1|\n|`diagnoses_icd`    |MIMIC-IV (hosp)      |Diagnózy ICD přiřazené hospitalizacím; zdroj štítků klasifikace.               |  6 364 488|       5|    34|\n|`discharge`        |MIMIC-IV-Note (note) |Propouštěcí zprávy; primární korpus práce.                                     |    331 793|       8| 1 139|\n|`omr`              |MIMIC-IV (hosp)      |Ambulantní měření (například výška, hmotnost, tlak); kontext zprávy.           |  7 753 027|       5|    44|\n|`patients`         |MIMIC-IV (hosp)      |Pacienti: pohlaví, věk a rok ukotvení; podklad dělení dat po pacientech.       |    364 627|       6|     3|\n|`pharmacy`         |MIMIC-IV (hosp)      |Lékárenské záznamy o lécích; kontext zprávy.                                   | 17 847 567|      27|   526|\n|`prescriptions`    |MIMIC-IV (hosp)      |Předpisy léků; kontext zprávy.                                                 | 20 292 611|      21|   606|\n|`procedures_icd`   |MIMIC-IV (hosp)      |Výkony ICD přiřazené hospitalizacím; kontext zprávy.                           |    859 655|       6|     8|\n|`radiology`        |MIMIC-IV-Note (note) |Radiologické zprávy; doplňkový korpus.                                         |  2 321 355|       8|   782|\n|`services`         |MIMIC-IV (hosp)      |Služby, na kterých pacient během hospitalizace ležel; kontext zprávy.          |    593 071|       5|     9|\n\n\n:::\n:::\n\n\n*Zdroj:* počty záznamů dotazem v DuckDB, počty sloupců a velikosti souborů z manifestu validace, popisy podle veřejné dokumentace MIMIC-IV a MIMIC-IV-Note.\n\nPodle návrhu práce je primárním korpusem tabulka `discharge`; obsahuje 331 793 záznamů. Radiologických zpráv je v tabulce `radiology` 2 321 355. Nejvíce záznamů má tabulka prescriptions. Počty záznamů v databázi se shodují s počty v manifestu validace.\n\n# Shrnutí a rozhodnutí {#sec-shrnuti}\n\nDokument popsal zdroje dat, cestu dat k dotazování a přehled 12 tabulek. Počty záznamů se u všech tabulek shodují s manifestem validace. Data jsou proto úplná a další části analýzy mohou stavět na parquetu bez další kontroly počtu záznamů.\n\n# Omezení {#sec-omezeni}\n\nPřehled uvádí jen počty záznamů, sloupců a velikosti souborů. O obsahu zpráv, pacientech ani rozdělení dat netvrdí nic; to je předmětem dalších částí analýzy. Počty se vztahují k verzím 3.1 (MIMIC-IV) a 2.2 (MIMIC-IV-Note). Potlačení kategorií s n < 10 chrání malé skupiny, ale nezabraňuje odvození z rozdílu dvou zveřejněných součtů, proto se zveřejňují jen předem určené agregace. Automatizovaná kontrola neprohledává text uvnitř obrázků, proto grafy vyžadují zvláštní zacházení.\n\n# Příloha A: provenance renderu {.unnumbered}\n\n@tbl-provenance uvádí údaje, podle kterých lze render dohledat a zopakovat: revizi kódu, otisk zámku prostředí, zdroj dat a verze použitých nástrojů.\n\n\n\n\n::: {#tbl-provenance .cell tbl-cap='Provenance renderu.' tbl-colwidths='[28,72]'}\n::: {.cell-output-display}\n\n\n|Položka                                 |Hodnota                                                             |\n|:---------------------------------------|:-------------------------------------------------------------------|\n|Revize kódu (commit)                    |b1c79ebae4ba3c50fd7c987e45f50b24a038bd81                            |\n|Necommitnuté změny                      |ne                                                                  |\n|Otisk pixi.lock (SHA-256)               |fddaa503186e36c9 6a2da977486f402d 47bdea58afdc3972 b154c8c586a0e4ca |\n|Zdroj dat                               |otisky CSV z config/mimic_tables.json                               |\n|Otisk discharge.csv.gz (SHA-256)        |27bc552edaf81c2a f322040cb7e8eb36 417173b23c79405b b92fcf73bef2dbc5 |\n|Otisk radiology.csv.gz (SHA-256)        |2c09bc76ee12d5f3 b8f572deb7218fba f3e59b32eccfdae1 4686e05ae099eebb |\n|Otisk admissions.csv.gz (SHA-256)       |a9584ed88e9ed664 a2f66f86a5cf9fd1 75c8bb0af50e3b61 15598b19e978384e |\n|Otisk d_icd_diagnoses.csv.gz (SHA-256)  |a81065bf45ccf74f 589bec855bbb0a07 b5c014907b34ff76 fe20583a2c87cc79 |\n|Otisk d_icd_procedures.csv.gz (SHA-256) |a2ac8afcb99fd16b ce2e6c7ad445e3bd 1dfd658e52182313 0ab08b66fdd3d6d4 |\n|Otisk diagnoses_icd.csv.gz (SHA-256)    |47665a41b2a3ad99 0d6f314062d5bd6d 29d467b0fd402dd9 4662044ec8b073d2 |\n|Otisk omr.csv.gz (SHA-256)              |8280a8023203bddc 6cc4419bd8cd253a 015b8bc0bc53852e c92f98c7353f31e2 |\n|Otisk patients.csv.gz (SHA-256)         |4c7507de7ecad8c5 ba7647ea4d26018e 88ff6672c5fc22ab 59c2a5697d687cdd |\n|Otisk pharmacy.csv.gz (SHA-256)         |c9885721e4c968f0 773145d7f6ba4d3c c3755d5600ee400f f95b1d3238053811 |\n|Otisk prescriptions.csv.gz (SHA-256)    |0d8481c7d5d7c9ec 2fea3fc543ddaaad b5a933cd22c7b9dd a4289361e4d77199 |\n|Otisk procedures_icd.csv.gz (SHA-256)   |3271397d0517131f 84399b698cbb0c2f 435aaab0f873a380 6e13b097661596f7 |\n|Otisk services.csv.gz (SHA-256)         |31c82ebee94e0c04 d6966fbfec30579e c00f9c7816b80852 f9580656e6183888 |\n|Python                                  |3.13.16                                                             |\n|DuckDB                                  |1.5.6                                                               |\n|R                                       |R version 4.5.3 (2026-03-11)                                        |\n\n\n:::\n:::\n\n\n# Literatura {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}